### ISSUE TITLE
This script is working when I execute it from bash but not working if executed from a java program

### ISSUE THREAD

**Issue by soham0243** [abiyani/automate-save-page-as#29]
![Screenshot (31)](https://user-images.githubusercontent.com/58434045/69972528-c69ae280-14ef-11ea-9fec-4419b9b32ea5.png)
This bash script does not run as it should.

**Comment by abiyani** [comment]
You will need to provide more information:

1. What does the error message / behavior look like?
2. How are you running the script? In particular, is there an active X-server running on the machine?
3. What happens if you just run `google-chrome` for example as your `command` in the Java program above? Does it launch Chrome correctly on the machine when the program runs?

**Comment by soham0243** [comment]
1. It does not show any error message. Just an empty field is shown
2. No there is no active x server running on the machine.
3. I don't have google chrome in linux installed. I only have firefox browser. firefox didn't start when I ran it from java program.
Note: I resolved this issue using processbuilder object in java.
Anyway, thanks for your reply.
